CREATE TABLE IF NOT EXISTS products (
 id BIGSERIAL PRIMARY KEY,
 name TEXT NOT NULL,
 category TEXT NOT NULL,
 price NUMERIC(12,2) NOT NULL DEFAULT 0,
 old_price NUMERIC(12,2) NOT NULL DEFAULT 0,
 stock INTEGER NOT NULL DEFAULT 0,
 image TEXT NOT NULL DEFAULT '',
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGSERIAL PRIMARY KEY,
 order_no TEXT UNIQUE NOT NULL,
 customer_name TEXT NOT NULL,
 phone TEXT NOT NULL,
 address TEXT NOT NULL,
 area TEXT NOT NULL,
 note TEXT NOT NULL DEFAULT '',
 payment TEXT NOT NULL DEFAULT 'Cash on Delivery',
 delivery_zone TEXT NOT NULL,
 delivery_charge NUMERIC(12,2) NOT NULL DEFAULT 0,
 subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
 grand_total NUMERIC(12,2) NOT NULL DEFAULT 0,
 status TEXT NOT NULL DEFAULT 'New',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_items (
 id BIGSERIAL PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
 product_id BIGINT NOT NULL REFERENCES products(id),
 product_name TEXT NOT NULL,
 price NUMERIC(12,2) NOT NULL,
 quantity INTEGER NOT NULL,
 line_total NUMERIC(12,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS shop_settings (
 id INTEGER PRIMARY KEY DEFAULT 1,
 shop_name TEXT NOT NULL DEFAULT 'মাহমুদ টেলিকম',
 phone TEXT NOT NULL DEFAULT '01846-655270',
 whatsapp TEXT NOT NULL DEFAULT '8801846655270',
 delivery_inside NUMERIC(12,2) NOT NULL DEFAULT 60,
 delivery_outside NUMERIC(12,2) NOT NULL DEFAULT 120,
 cod BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO shop_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;
